---
- hosts: dockerhost

  tasks:
   - name: stop existing container
     command: docker stop regapp-server
     ignore_errors: yes

   - name: remove the container
     command: docker rm regapp-server
     ignore_errors: yes

   - name: remove image
     command: docker rmi osamah9/regapp:latest
     ignore_errors: yes

   - name: remove none images
     command: docker image prune -f
     ignore_errors: yes

   - name: create container
     command: docker run -d --name regapp-server -p 8082:8080 osamah9/regapp:latest
